name: Pushing to Docker Hub

on: 
  push:
    branches: main

jobs:
  PushingCodeToDocker:
    runs-on: ubuntu-latest
  
    steps:
      - name: Hello Docker
        run: echo "Hello Docker"
    
      - name: Pushing our code to Docker Hub
        run: |
          echo "Secrets" ${{secrets}}
          echo ${{secrets.DOCKER_USER_NAME}} ${{secrets.DOCKER_PASSWORD}}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Exploring Host Machine
        run: |
          echo 'Current Dir'
          pwd
          echo 'Home'
          cd /
          ls -la 
          
          

      

      

        

  PushingCodeToDockerJob2:
    runs-on: ubuntu-latest

    steps:
      - name: Running Docker Job 2
        run: echo "Job 2"

      
  
