name: Continous Integration testing
on:
  push:

jobs:
  testing-ci:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout Code
        uses: action/checkout@v4

      - name: Setting up python
        uses: action/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies for my tesint
        run: pip install pytest
          

  
     
    
